title: Deepin en Español
# Original: https://deepin-espanol.gitlab.io
url: "http://deepin.ovh"
baseurl: ""
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:
pluscomments: true
official_url: http://deepin.ovh/
logo: /images/favicon/favicon-32x32.png
lang: ES

# Default description in social shares for the jekyll-seo-tag gem
# Desactivado por añadir la descripción al título y superar el limite de caracteres
# description:

# Author details for the jekyll-seo-tag gem
author:
  name: Deepin en Español
  email:
  twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Deepin en Español
  links:
    - https://deepin.ovh
    - https://telegram.me/deepinenespanol

# Colecciones
collections:
  staff_members:
    output: false
  actividads:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: /:categories/:title/

jekyll-archives:
  enabled:
    - "categories"

#Plugins, antes gemas
plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate-v2-redux"
  - "jekyll-archives"
  - "emoji_for_jekyll"
  - "jekyll-email-protect"
  - "jekyll-sitemap"

#Renderizado
markdown: kramdown
highlighter: rouge

#Desarrollo de páginas
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "actividads"
    values:
      layout: "actividad"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# ---------
# Comprimir contenido (compress_html y sass)

compress_html:
  clippings: all
  comments:  all
  endings:   all
  startings: [html, head, body]

sass:
  sass_dir: _sass
  style: compressed

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Telegram
  - Tumblr
  - Twitter
  - YouTube
  - RSS

# --------------
# Icons

favicon-32x32:                          'favicon-32x32.png'
touch-icon-192x192:                     'touch-icon-192x192.png'
apple-touch-icon-180x180-precomposed:   'apple-touch-icon-180x180-precomposed.png'
apple-touch-icon-152x152-precomposed:   'apple-touch-icon-152x152-precomposed.png'
apple-touch-icon-144x144-precomposed:   'apple-touch-icon-144x144-precomposed.png'
apple-touch-icon-120x120-precomposed:   'apple-touch-icon-120x120-precomposed.png'
apple-touch-icon-114x114-precomposed:   'apple-touch-icon-114x114-precomposed.png'
apple-touch-icon-76x76-precomposed:     'apple-touch-icon-76x76-precomposed.png'
apple-touch-icon-72x72-precomposed:     'apple-touch-icon-72x72-precomposed.png'
apple-touch-icon-precomposed:           'apple-touch-icon-precomposed.png'
msapplication_tileimage:                'msapplication_tileimage.png'               # Size 144x144
msapplication_tilecolor: '#fabb00'

#--------
# Exclusión

exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
